### ISSUE TITLE
getter functions in class

### ISSUE THREAD

**Issue by enesbilik** [taqanarslan/MobiLab#3]
https://github.com/taqanarslan/MobiLab/blob/23bd0e50824b73390380e976402a458d7233b496/odev1/Behzat/lib/widgets/boxes/box_widget.dart#L3

It would be more accurate to define it as a getter function within the class instead of defining it globally.

`class CustomWidget {
Widget get sizedBox30 => const SizedBox(height: 30); 
}
`

**Comment by behzodfaiziev** [comment]
@enesbilik resolved issue by commit `f78c211`. 
Thx for the remark
